app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categories(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categories SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categories WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categories WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categories"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categories"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/forms/category_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class CreateCategoryForm(FlaskForm):
    category = StringField('Categoría', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripción', 
                              validators=[DataRequired()])
    submit = SubmitField('Guardar')
class UpdateCategoryForm(FlaskForm):
    category = StringField('Categoría', 
                           validators=[DataRequired()])
    description = TextAreaField('Descripción', 
                              validators=[DataRequired()])
    submit = SubmitField('Actualizar')

app/views/category_views.py
from flask import Blueprint, render_template, redirect, url_for

from models.categories import Category

category_views = Blueprint('category', __name__)

from forms.category_forms import CreateCategoryForm, UpdateCategoryForm
@category_views.route('/categories/')
def categories():
    cats = Category.get_all()
    return render_template('category/categories.html', cats=cats)

@category_views.route('/categories/create/', methods = ('GET', 'POST'))
def create_cat():
    form = CreateCategoryForm()
    if form.validate_on_submit():
        category = form.category.data
        description = form.description.data
        cat = Category(category, description)
        cat.save()
        return redirect(url_for('category.categories'))
    return render_template('category/create_cat.html', form=form)

@category_views.route('/categories/<int:id>/update/', methods = ('GET', 'POST'))
def update_cat(id):
    form = UpdateCategoryForm()
    cat = Category.get(id)
    if form.validate_on_submit():
        cat.category = form.category.data
        cat.description = form.description.data
        cat.save()
        return redirect(url_for('category.categories'))
    form.category.data = cat.category
    form.description.data = cat.description
    return render_template('category/create_cat.html', form=form)

@category_views.route('/categories/<int:id>/delete/', methods = ('POST',))
def delete_cat(id):
    cat = Category.get(id)
    cat.delete()
    return redirect(url_for('category.categories'))

app/templates/category/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}

{% block content %}
<table id="categories">
    <a href="{{ url_for('category.create_cat' ) }}" class="btn">Nueva Categoria</a>
    <thead>
        <tr>
            <th>ID</th>
            <th>Categoria</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in cats %}
        <tr>
            <td>{{ cat.id }}</td>
            <td>{{ cat.category }}</td>
            <td>{{ cat.description }}</td>
            <td>
            <a href="{{ url_for('category.update_cat', id=cat.id) }}">
                <i class="fa fa-pencil "></i>
            </a>
            <form 
            method="post"
            action="{{ url_for('category.delete_cat', id=cat.id) }}">
            <button
            onclick ="return confirm('Seguro?')"
            type="submit">
            <i class="fa fa-trash"></i>
            </button>
        </form>
            </td>
        </tr>        
        {% endfor %}
    </tbody>
</table>
    {% endblock %}

app/templates/category/create_cat.html
{% extends 'base.html' %}

{% block title %}
Crear Nueva Categoría
{% endblock %}
{% block content %}
<form method="post">

        {{ form.csrf_token }}
        
        <div>
                {{ form.category.label }}
                {{ form.category() }}
                {% if form.category.errors %}
                {% for error in form.category.errors %}
                <p>{{ error }}</p>
                {% endfor %}
                {% endif %}
        </div>
        
        <div>
                {{ form.description.label }}
                {{ form.description() }}
                {% if form.description.errors %}
                {% for error in form.description.errors %}
                <p>{{ error }}</p>
                {% endfor %}
                {% endif %}
                
        </div>
        <div>
                {{ form.submit(class="btn") }}
        </div>
        
</form>
{% endblock %}