app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categories(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categories SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categories WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categories WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categories"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categories"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/views/home_views.py
from flask import Blueprint, render_template

home_views = Blueprint('home', __name__)


@home_views.route("/")


@home_views.route("/home/")
def home():
    return render_template('home/home.html')

@home_views.route("/contact/")

def contact():
    return render_template('home/contact.html')

@home_views.route("/saludo/<name>/")
def saludo(name):
    user='admin'
    return render_template(
        'home/saludo.html',
        name=name,
        user=user)

@home_views.route("/drinks/")
def drinks():
    drinks = ["agua","tequila","jugo", "Pulque", "Cheve"]    
  
    return render_template('home/drinks.html',drinks=drinks)

app/views/user_views.py
from flask import Blueprint, redirect, render_template, url_for, flash, abort

from models.users import User

from forms.user_forms import LoginForm, RegisterForm, ProfileForm

from utils.file_handler import save_image

user_views = Blueprint('user', __name__)

@user_views.route('/users/register/', methods=('GET', 'POST'))
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data

        user = User(username, password, email)
        user.save()

        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)

@user_views.route('/users/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            return render_template('home/home.html', user=user)
    return render_template('user/login.html', form=form)

@user_views.route('/users/<int:id>/profile/', methods=('GET', 'POST'))
def profile(id):
    form = ProfileForm()
    user = User.__get__(id)
    if not user:
        abort(404)
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        f = form.image.data
        if f:
            user.image = save_image(f, 'images/profiles', user.username)
        user.save()
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    image = user.image
    return render_template('user/profile.html', form=form, image=image)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title> {% block tittle %} {% endblock %} </title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{ url_for('home.home') }}">Home</a></li>
            <li><a href="{{ url_for('home.contact') }}">Contatc</a></li>
            <li><a href="{{ url_for('home.saludo', name='Ismael') }}">Saludo</a></li>
            <li><a href="{{ url_for('home.drinks') }}">Drinks</a></li>
            <li><a href="{{ url_for('category.categories') }}">Categorias</a></li>
            <li> <a href="{{url_for('user.register')}}">Registro</a></li>
            {% if user %}
            <li><a href="#">Logout</a></li>
            {% else %}
            <li><a href="{{url_for('user.login')}}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    
    <div class="container">

        
        {% block content %}
        
        {% endblock %}
    </div>

    <footer>
        <p>Copyright @Ismabb</p>
    </footer>
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}

{% block content %}
<table id="categories">
    <a href="{{ url_for('create_cat' ) }}" class="btn">Nueva Categoria</a>
    <thead>
        <tr>
            <th>ID</th>
            <th>Categoria</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in cats %}
        <tr>
            <td>{{ cat.id }}</td>
            <td>{{ cat.category }}</td>
            <td>{{ cat.description }}</td>
            <td>
            <a href="{{ url_for('update_cat', id=cat.id) }}">
                <i class="fa fa-pencil "></i>
            </a> 
            <a href="{{ url_for('delete_cat', id=cat.id) }}">
                <i class="fa fa-trash "></i>
            </a>
            </td>
        </tr>        
        {% endfor %}
    </tbody>
</table>
    {% endblock %}